#!/bin/sh
./liquibase --classpath=/liquibase/lib/postgresql-9.4.1208.jar:/liquibase/changelogs  --username=$DB_USER --password=$DB_PASS --driver=org.postgresql.Driver --url=jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME --changeLogFile=db.changelog-master.xml "$@"

